spring:
  profiles:
    active: local
    include: secret
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    hiddenmethod: # @DeleteMapping 사용 위해
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  cache:
    type: simple
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #  show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500

server:
  tomcat:
    use-relative-redirects: true
logging.level:
  org.hibernate.SQL: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
